networks:
  saludconecta-citas-network:
    driver: bridge
  kafka:
    driver: bridge

volumes:
  database_data:

services:
  database:
    image: mongo:7
    container_name: database
    networks:
      - saludconecta-citas-network
    ports:
      - "27017:27017"
    volumes:
      - database_data:/data/db

  citas-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: citas-app
    depends_on:
      - database
    networks:
      - saludconecta-citas-network
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://database:27017/citasdb
      KAFKA_BOOTSTRAP_SERVERS: broker-1:19092,broker-2:19092,broker-3:19092
