@startuml Empleado

skinparam maxMessageSize 100
skinparam wrapWidth 400

[*] --> Disponible : El empleado se da de alta en el sistema, proporcionando sus datos personales o importándolos de un sistema externo.

Disponible : El empleado está activo en el sistema, tiene un rol asignado y está disponible para asignarle un turno
Disponible --> Trabajando : El empleado empieza su turno en el hospital
Disponible --> Baja : El empleado solicita una baja temporal por motivos personales o profesionales
Disponible --> Suspendido : El empleado comete una falta grave y es suspendido temporalmente
Disponible --> Retirado : El empleado solicita su baja definitiva en el hospital o alcanza la edad de jubilación

Trabajando : El empleado está actualmente trabajando en el hospital y cumpliendo con sus responsabilidades
Trabajando --> Disponible : El empleado finaliza su turno en el hospital
Trabajando --> Baja : El empleado sufre un accidente laboral mientras realiza su turno
Trabajando --> Suspendido : El empleado comete una falta grave durante su turno

Baja : El empleado está de baja temporal por motivos personales o profesionales
Baja --> Disponible : El empleado se reincorpora a su puesto de trabajo
Baja --> Suspendido : El empleado comete una falta grave durante su baja

Suspendido : El empleado está suspendido temporalmente por motivos disciplinarios
Suspendido --> Disponible : La dirección del hospital levanta la suspensión
Suspendido --> Retirado : La dirección del hospital decide retirar al empleado del hospital

Retirado : El empleado ha dejado de trabajar en el hospital
Retirado --> [*] : El empleado es eliminado del sistema (sus datos se archivan)

@enduml